version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/dbScraping
      - JWT_SECRET=@4bG7!fZsP3wH9#M
      - SESSION_SECRET=Y6n%8kPq@1#4!vTz
      - COOKIE_SECRET=M4%rSfwh8:eAztq
      - CSRF_SECRET=P$rN5o+AZ1H]~Bk
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=dbScraping
