name: Deploiement sur vps

on:
  push:
    branches:
      - main

jobs:
  deploy-to-vps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: api2.camille-lecoq.com
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Arrêter et supprimer tous les conteneurs Docker
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)
          
          # Supprimer toutes les images Docker
          docker rmi $(docker images -q) -f
          
          # Supprimer l'ancien dossier du projet si existant
          [ -d "web-api" ] && rm -rf web-api
          
          # Cloner le dépôt
          git clone https://github.com/Dinoozz/ScrapService.git web-api
          
          # Aller dans le dossier du projet et lancer Docker Compose
          cd web-api
          docker compose up --build
